image: computermouth/sudeb

before_script:
  - sudo apt-get update -qq

setup:
  script:
    - sudo apt-get install -y binfmt-support curl wget qemu-user-static
    - sudo update-binfmts --enable
    - sudo update-binfmts --enable qemu-arm
    - ./build.sh -a
  artifacts:
    paths:
      - rootfs.tar.gz
